--- 
clone: 
  depth: 1
kind: pipeline
name: EvaPipeline
steps: 
  - name: Kernel Pipeline
    image: ubuntu:focal
    commands: 
      - apt update && apt -y install bc libssl-dev python2 build-essential make git python curl wget zip flex bison
      - "export token=$TOKEN"
      - "bash cannon-build.sh"
    environment: 
      TOKEN: 
        from_secret: token
    trigger: 
      branch:
        - eva 