name: Kernel Build CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Kernel
        run: |
          pacman -Syu --needed --noconfirm inetutils bc cpio git
          git config --global --add safe.directory /__w/kernel_xiaomi_cannon/kernel_xiaomi_cannon
          export token=${TELEGRAM_BOT_TOKEN}
          bash cannon-build.sh
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
